config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
    resources :viewers, controller: "article_viewers"
  end

  root 'welcome#index'

  # 不区分get post这不好
  # match ':controller(/:action(/:id(.:format)))', :via => :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :viewers
  validates :title, presence: true,
            length: {minimum: 5}
end

app/models/viewer.rb
class Viewer < ApplicationRecord
  validates :name, presence: true
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_viewers_controller.rb
class ArticleViewersController < ApplicationController
  before_action :set_article

  def index
    @viewers = @article.viewers
  end

  def show
    @viewer = @article.viewers.find(params[:id])
  end

  def new
    @viewer = @article.viewers.build
  end

  def create
    @viewer = @article.viewers.build(viewer_params)
    if @viewer.save
      flash[:notice] = "新增成功"
      redirect_to article_viewers_path(@article)
    else
      flash[:alert] = "新增失败"
      render 'new'
    end
  end

  def edit
    @viewer = @article.viewers.find(params[:id])
  end

  def update
    @viewer = @article.viewers.find(params[:id])
    if @viewer.update(viewer_params)
      flash[:notice] = "更新成功"
      redirect_to article_viewers_path(@article)
    else
      flash[:alert] = "更新失败"
      render 'edit'
    end
  end
  def destroy
    @viewer = @article.viewers.find(params[:id])
    @viewer.destroy
    redirect_to article_viewers_path(@article)
  end
  protected

  def set_article
    # 必须用　article_id, 因为 id 现在默认为　viewer的
    @article = Article.find(params[:article_id])
  end

  def viewer_params
    params.require(:viewer).permit(:name)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  # GET /articles/:id/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles/:id/edit
  def update
    @article = Article.find(params[:id])
    # 更新
    if @article.update(article_params)
      # redirect_to @article
      # 成功了去的路由 show
      redirect_to article_path(@article)
    else
      # 失败了　不能用redirect 只能用render, 因为redirect 　在错误之前编辑的东西就没了
      render action: :edit
    end
  end

  # GET /articles/:id/show
  def show
    @article = Article.find(params[:id])
    @article_status = @article.status
  end

  def new
    #　初始化空的article
    @article = Article.new
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:alert] = "删除成功"
    redirect_to articles_path(@article)
  end

  # POST /articles/create
  # 因为是表单过来的,所以是post
  def create
    @article = Article.new(article_params)

    if @article.save
      # redirect_to @article
      # 成功了去的路由
      flash[:notice] = "新增成功"
      redirect_to articles_path(@article)
    else
      flash[:alert] = "新增失败"
      render 'new'
    end
  end

  private


  # strong parameter
  def article_params
    params.require(:article).permit(:title, :text, :status)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_viewers_helper.rb
module ArticleViewersHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/article_viewers/_form.html.erb
<% if @viewer.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@viewer.errors.count,"error")  %>
      prohibited this article from being saved:
    </h2>
    <ul>
      <% @viewer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :name , "访客姓名"%>
<%= f.text_field :name %>

<%= f.submit "提交"%>

app/views/article_viewers/edit.html.erb
<%= form_for @viewer, url: article_viewer_path(@article), mathod: :patch do |f| %>
  <%= render partial: "form", locals: {f: f} %>
<% end %>

<%= link_to '返回', article_viewers_path(@article) %>

app/views/article_viewers/index.html.erb
<h2> <%= @article.title %>: viewer list </h2>

<table>
  <tr>
    <th>访客</th>
    <th>最初访问</th>
    <th>最近访问</th>
  </tr>
  <% @viewers.each do |viewer| %>
    <tr>
    <td><%= viewer.name %></td>
    <td><%= viewer.created_at %></td>
    <td><%= viewer.updated_at %></td>
      <td>  <%= link_to "展示", article_viewer_path(@article, viewer) %></td>
      <td> <%= link_to "再次访问", edit_article_viewer_path(@article, viewer) %></td>
      <td> <%= link_to "删除访客", article_viewer_path(@article, viewer), method: :delete %></td>

    </tr>
  <% end %>
</table>

<%= link_to '新增访客', new_article_viewer_path(@article) %> <br>
<%= link_to '返回', articles_path %>

app/views/article_viewers/new.html.erb
<%=form_for @viewer, url: article_viewers_path(@article) do |f| %>
  <%= render partial: "form" , locals: { f: f }   %>
<% end %>
<%= link_to '返回', article_viewers_path(@article) %>

app/views/article_viewers/show.html.erb
<h2> title: <%= @article.title %> </h2>

<p>
  <%= @viewer.name %>
</p>

<%= link_to "返回", article_viewers_path(@article) %>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count,"error")  %>
      prohibited this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<p>
  <%= f.label :title ,"标题"%><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text ,"文本"%><br>
  <%= f.text_area :text %>
</p>

<p>
  <%= f.label :status ,"状态"%><br>
  <%= f.text_area :status %>
</p>
<p>
  <%= f.submit "提交"%>
</p>

app/views/articles/edit.html.erb
<h1>更改博客</h1>

<%= form_for @article, url: article_path(@article), mathod: :patch do |f| %>
    <%= render partial: "form" , locals: { f: f }   %>
<% end %>

<%= link_to '返回', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<!--debug打印出来-->
<%#=debug(@articles[0]) %>

<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Viewers', article_viewers_path(article) %></td>
<!--      <td><%#= link_to 'Edit', controller: 'articles', action:  'edit', id: article  %></td>-->
      <td><%= link_to 'Edit',  edit_article_path(article)  %></td>
<!--      delete 在 rails4　之后　都只能按　method写, 否则还是走GET路由 -->
      <td><%= link_to 'Delete', article_path(article) ,method: :delete   %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>新增博客</h1>

<%= form_for :article, url: articles_path  do |f| %>
  <%= render partial: "form" , locals: { f: f }   %>
<% end %>

<%= link_to '返回', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
<!--  出现换行　simple_format　-->
  <%= simple_format @article.text %>
  <%#=  @article.text %>
</p>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--    注意要给　运算区域里的　字符串加" "-->
  <title><%= @article_status || "Blog" %> </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<!--flash信息只会出现一次-->
<p style="color: green"> <%= flash[:notice] %> </p>
<p style="color: red"> <%= flash[:alert] %> </p>
<%= yield %>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>